config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :file_records do
    member do
      get 'inci_score'
    end

    collection do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "file_records#index"
  # root "home#index"
  root "file_records#index"
  # get '/inci_score', to: 'file_records#inci_score', as: 'inci_score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_record.rb
class FileRecord < ApplicationRecord
	acts_as_tenant(:user)
	mount_uploader :file, SheetUploader
	validates :name,:file, presence: true
	has_many :inci_records
end

app/models/inci_record.rb
class InciRecord < ApplicationRecord
	belongs_to :file_record
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	set_current_tenant_through_filter
  	before_action :set_tennant

  	def set_tennant
    	set_current_tenant(current_user)
  	end
end

app/controllers/file_records_controller.rb
class FileRecordsController < ApplicationController
  before_action :set_file_record, only: %i[ show edit update destroy inci_score ]

  # GET /file_records or /file_records.json
  def index
    @file_records = FileRecord.all
  end

  # GET /file_records/1 or /file_records/1.json
  def show
  end

  # GET /file_records/new
  def new
    @file_record = FileRecord.new
  end

  # GET /file_records/1/edit
  def edit
  end

  # POST /file_records or /file_records.json
  def create
    @file_record = FileRecord.new(file_record_params)
    @file_record.user_id = current_user.id

    respond_to do |format|
      if @file_record.save
        format.html { redirect_to file_records_path, notice: "File record was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @file_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_records/1 or /file_records/1.json
  def update
    respond_to do |format|
      if @file_record.update(file_record_params)
        format.html { redirect_to @file_record, notice: "File record was successfully updated." }
        format.json { render :show, status: :ok, location: @file_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @file_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_records/1 or /file_records/1.json
  def destroy
    @file_record.destroy
    respond_to do |format|
      format.html { redirect_to file_records_url, notice: "File record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def inci_score
    require 'roo'
    require "inci_score"
    @file_record.inci_records.destroy_all
    @inci_records=[]
    index=0
    $i=2
    excel = Roo::Spreadsheet.open(@file_record.file.path)
    sheets = excel.sheets
    sheets.each do |sheet|
      while $i <= excel.sheet(sheet).last_row  do
        composition = excel.sheet(sheet).row($i)
        inci = InciScore::Computer.new(src: composition[2]).call
        score = inci.score
        unrecognized = inci.unrecognized
        @obj = InciRecord.create(product:composition[0],score:score,composition:composition[2],unrecognized_inci:unrecognized,reference:composition[1],file_record_id:@file_record.id)
        puts("Inside the loop i = #$i" )
        $i +=1
        @inci_records.push(@obj)
      end
    end
    # @inci_records = @file_record.inci_records
    respond_to do |format|
      format.html{
      }
      format.pdf do
        render pdf: "file_name"   # Excluding ".pdf" extension.
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_record
      @file_record = FileRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def file_record_params
      params.require(:file_record).permit(:name, :file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	require "inci_score"
	debugger
	inci = InciScore::Computer.new(src: 'aqua, dimethicone').call
	inci.score # 53.7629
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_records_helper.rb
module FileRecordsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_records/_form.html.erb
<%= form_for @file_record, :html => {:multipart => true} do |form| %>
  <% if file_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_record.errors.count, "error") %> prohibited this file_record from being saved:</h2>

      <ul>
      <% file_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name,class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file,class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit',class:'btn btn-success' %>
  </div>
<% end %>

app/views/file_records/edit.html.erb
<h1>Editing File Record</h1>

<%= render 'form', file_record: @file_record %>

<%= link_to 'Show', @file_record %> |
<%= link_to 'Back', file_records_path %>

app/views/file_records/inci_score.html.erb
<%if @inci_records.present?%>
<a href="<%=inci_score_file_record_path(@file_record,format: :pdf)%>" target='_blank' class='btn btn-default'>Generate PDF</a>
<hr>
<%end%>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Product(s)</th>
			<th>Score</th>
			<th>UnRecognized Inci</th>
			<th>Composition</th>
			<th>Reference</th>
		</tr>
	</thead>
	<tbody>
		<%@inci_records.each do |inci_record|%>
			<tr>
				<td><%=inci_record.product%></td>
				<td><%=inci_record.score%></td>
				<td><%=inci_record.unrecognized_inci.join(",")%></td>
				<td><%=inci_record.composition%></td>
				<td><%=inci_record.reference%></td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/file_records/inci_score.pdf.erb
 <style type="text/css">
.my_table{
  border: 2px solid;
  width:100%;
}
.my_table td{
  padding-left: 2px;
  border: 1px solid;
}
.my_table th{
  padding-left: 2px;
  border: 2px solid;
}
    </style>
<table class="table table-bordered my_table">
	<thead>
		<tr>
			<th>Product(s)</th>
			<th>Score</th>
			<th>UnRecognized Inci</th>
			<th>Composition</th>
			<th>Reference</th>
		</tr>
	</thead>
	<tbody>
		<%@inci_records.each do |inci_record|%>
			<tr>
				<td><%=inci_record.product%></td>
				<td><%=inci_record.score%></td>
				<td><%=inci_record.unrecognized_inci.join(",")%></td>
				<td><%=inci_record.composition%></td>
				<td><%=inci_record.reference%></td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/file_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>File Records</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th>options</th>
    </tr>
  </thead>

  <tbody>
    <% @file_records.each do |file_record| %>
      <tr>
        <td><%= file_record.name %></td>
        <td><%= link_to 'Download origional File',file_record.file.url,class:'btn btn-default btn-xs' %></td>
        <td>
          <%= link_to 'Edit', edit_file_record_path(file_record),class:'btn btn-default btn-xs' %>|
          <%= link_to 'Generate Inci Score', inci_score_file_record_path(file_record),class:'btn btn-default btn-xs' %>
        
          <a href="<%=inci_score_file_record_path(file_record,format: :pdf)%>" target='_blank' class='btn btn-default btn-xs'>Generate PDF</a>
        
          <%= link_to 'Destroy', file_record, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File Record', new_file_record_path,class:'btn btn-default' %>

app/views/file_records/new.html.erb
<h1>New File Record</h1>

<%= render 'form', file_record: @file_record %>

<%= link_to 'Back', file_records_path %>

app/views/file_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file_record.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @file_record.file %>
</p>

<%= link_to 'Edit', edit_file_record_path(@file_record) %> |
<%= link_to 'Back', file_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Costajob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Inci Catalogs Score </a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="<%=new_file_record_path%>">New Sheet</a></li>
          <li><a href="<%=file_records_path%>">View Record</a></li>
          <li><%= link_to "log out", destroy_user_session_path, method: :delete,class:'btn btn-xs btn-default' %></li>
        </ul>
      </div>
    </nav>
  
    <div class="container">
      <%= yield %>
    </div>
    <footer class="bg-default text-center">
      &copy; 2020 Some copyright message.
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Costajob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      .center {
      margin: auto;
      width: 50%;
      border: 3px solid green;
      padding-left: 50px;
      padding-right: 50px;
      border-radius: 10px;
       box-shadow: 10px 10px 5px lightgrey;
       background-color: cornsilk;
      }
    </style>
  </head>

  <body>
    <div class="center">
      <br>
      <%if notice.present?%>
        <p class="notice alert alert-info"><%= notice %></p>
      <%end%>
      <%if alert.present?%>
        <p class="alert alert alert-warning"><%= alert %></p>
      <%end%>
      <%= yield %>
      <br>
    </div>
  </body>
</html>